name: Lint
on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: ${{ matrix.target }} (${{ matrix.platform.os }}/${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.label }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - supplier
          - reactor
        platform:
          - os: linux
            arch: amd64
            label: ubuntu-24.04
          - os: linux
            arch: arm64
            label: ubuntu-24.04-arm
          - os: windows
            arch: amd64
            label: windows-2025
        include:
          - target: grafana-export
            platform:
              os: linux
              arch: amd64
              label: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.target }}/go.mod
          cache-dependency-path: ${{ matrix.target }}/go.sum
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: ${{ matrix.target }}
